{% set version = "7.6" %}

package:
  name: neuron
  version: {{ version }}

source:
  fn: nrn-{{ version }}.tar.gz
  url: https://www.neuron.yale.edu/ftp/neuron/versions/v{{ version }}/nrn-{{ version }}.tar.gz
  sha256: 4feefda6a6ed1d8c5e03f61d4a57ecfa8385e2f935f335a546989dcc976fde5b
  patches:
    - detect-libedit.patch  # [osx]
    - libnrniv.patch
    - pkg-config-ncurses.patch
    - memacs.patch
    - nocarbon.patch  # [osx]
    - stdio-h.patch

build:
  number: 1000
  skip: true  # [win]
  run_exports:
    - pin_compatible("neuron", max_pin="x.x", min_pin="x.x")

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - bison
    - flex
    - pkg-config
    - libtool
  host:
    - python
    - cython
    - numpy
    - readline
    - ncurses
  run:
    - python
    - numpy
    - readline
    - ncurses

test:
  requires:
    - {{ compiler('c') }}
    - scipy
  files:
    - Nap_Et2.mod
  imports:
    - neuron
    - neuron.rxd

about:
  home: https://neuron.yale.edu
  license: BSD 3-Clause
  license_file: Copyright
  summary: NEURON is a simulator for models of neurons and networks of neuron.

extra:
  recipe-maintainers:
    - minrk
