travis:
  secure:
    BINSTAR_TOKEN: GxTgzsaMqX7gA42gh1d7qahE5TkBrODOr7oaYeqCOuSLL5lPIXGFnbO8OqrUNq1YaIUEhUHKMfWF50Y26y55grAhtXmg2lpDyYxbibyM+w5TuIgVd7LSefQq+g4nH/miuDIQB+4/NmuBeVK23fBQW6YvV8fLzxThFWddcrm/+RABX7QyceVcCjzg99Zv0VI/yilZVxB1quyi5a6tsM0//wnAxisXW4gszuau1VbhOvy8sQbi48jNj610B5AZLtGdLQeNjWsPP9BzMXVZNLVFlNtGWlkHFNQ14V/6vwZPMpcfnPnZKMdFbpQ1vujvMG/GLss4bOo08pBfYUAnHlkCi638ipvmqJQTc+cSiexqqPp9cCgXt7EUX1t4hSkN4SCCu+EdhRF2mTYwulPTaPws7ojkAVKVW7wDds0G5fqL9lEQy25ALxemCvhDfrnAVnNJccaPcBX2jvedCXuEg6sqrTgozEnvGZUXS5IZ3Wh34FZXdQUP2gHL8dbQ8WrRtUmZYtnlWhYXBajobKeXGEODq81OybEKkC1NfNOXItiJtoQ8hsGfsgV8NcVr5kLVF8LsyTfn9C8T6dpRr7ZUooJJU7KXVFaaSwcku/iBSSZzXcsVSgVMwAsUH6YLYdEpidmgEvdZLVWFh+BVmBp8My8cKd1RT8TLnbOnLM1lFAP02gw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
